- README.md
Just a small change to make it a bit cooler :)
> add travis badge; change title

- README.md
Clarify what has to be done in order to install Sipi.
Please merge this soon. My last pull request was ignored for 2 months and the during conflict resolutions some of my change were ignored ;-)
> docs(readme): Clarify installation instructions

- config/sipi.init-knora-test.lua
add the new error handling functions to the test config for Knora
> fix (adapt sipi.init-knora-test.lua) add new error handling functions

- .travis.yml
> build (travis) update kakadu for travis

- scripts/get_mediatype.lua
adding more mimetypes for non image file upload
> add text/xml to supported mimetypes

- config/sipi.config.lua
@retokromer Could you apply your changes to this branch? Once you are done, we can merge them back to `develop`.
> docs (typo)

- include/SipiImage.h
as per https://github.com/dhlab-basel/Sipi/pull/206
> correct typos

- manual/building.rst
added to docs how to compile with optimisation level 3
> docs (use optimization): compile Sipi with optimization level 3

- .travis.yml
- ext/expat/CMakeLists.txt
- ext/lcms2/CMakeLists.txt
- ext/png/CMakeLists.txt
- ext/xz/CMakeLists.txt
Fixes (I hope) the current Travis publish stage failure.
> build (travis): fix for travis stages

- config/sipi.fake-knora-test-config.lua
- scripts/get_mediatype.lua
- scripts/send_response.lua
- scripts/test_mediatype.lua
- test/e2e/test_02_server.py
This PR adds support for text files in the Lua upload script to be used with Knora.
> Support text files

- manual/building.rst
quick note as I stumble on it while building sipi
> doc: requires cmake 3

- ext/jpeg/CMakeLists.txt
> build (jpeg): change download link to bintray

- ext/exiv2/CMakeLists.txt
> build (exiv2): use bintray

- CMakeLists.txt
- cmake/Modules/FindOpenSSL.cmake
- ext/curl/CMakeLists.txt
- ext/expat/CMakeLists.txt
- ext/fmt/CMakeLists.txt
- ext/lua/CMakeLists.txt
- ext/luarocks/CMakeLists.txt
- ext/sqlite3/CMakeLists.txt
- manual/building.rst
- src/formats/SipiIOPng.cpp
- src/metadata/SipiExif.cpp
Updated all external libraries to the most recent ones, added a small bugfix to read PNG-images with invalid EXIF-data (as contributed by Loïc :-)  (try/catch around EXIV2-library call)
> Update external libs

- Dockerfile
> chore: fix dockerfile

- CMakeLists.txt
- config/sipi.init.lua
- include/SipiIO.h
- shttps/Global.h
- src/SipiHttpServer.cpp
- src/SipiImage.cpp
- src/formats/SipiIOJ2k.cpp
- src/formats/SipiIOTiff.cpp
- src/metadata/SipiEssentials.cpp
- test/e2e/test_02_server.py
- Fixed bug within EssentialMetadata
- added mimetype to knora.json (for PDFs etc.)
- resolves #302
> feature: Add mimetype to knora json response

- .github/workflows/main.yml
- .grenrc
This PR updates release notes by following closed PRs. The release notes depending on selected labels and it runs with Github actions on each published release.
> Update release notes on each release

- .dockerignore
- .github/workflows/main.yml
- Dockerfile
- Makefile
- requirements.txt
- test/integration/test_file_type_route.py
> DSP-707 First call to Sipi results in a prematurely closed TCP/IP connection

- .gitignore
- src/formats/SipiIOJ2k.cpp
- test/e2e/test_02_server.py
> fix: kakadu error

- mkdocs.yml
As suggested in #322 by @kilchenmann
> Add a link to the Sipi Github repository

- .github/workflows/main.yml
- docs/lua.md
- mkdocs.yml
resolves #348 
I added two steps to the github actions workflow:
* **docs-build-test** tries to build the documentation on each push
* **deploy-docs** deploys the documentation when a PR is merged into main branch (we will see if this step works, when we merge this PR)
> chore(gh-ci): automation of the documentation

- README.md
- docs/building.md
- docs/index.md
- docs/introduction.md
- docs/sipi.md
This PR contains the changes that @julsraemy did in his forked repo (#354)
> docs: update documentation

- shttps/Parsing.cpp
- shttps/sole.hpp
While fixing the file magic problem, this file was unintentionally deleted.
> fix: add missing file

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- Makefile
- src/SipiHttpServer.cpp
> fix(knora.json): return origin instead of wildcard (DEV-318)

- src/SipiHttpServer.cpp
the error message does not reflect the lua function that has actually been called
> fix: incorrect error message

- src/sipi.cpp
> refactor(sentry): turn off debug logging and configure sampling

- shttps/Server.cpp
- src/sipi.cpp
> refactor(sentry): change to auto sessions and introduce transactions

- src/SipiHttpServer.cpp
> fix: watermark support

- ext/bzip2/CMakeLists.txt
- ext/tiff/CMakeLists.txt
- ext/webp/CMakeLists.txt
> fix: Fix broken links and disable libwebp building its CLI tool

- docs/src/lua.md
- include/Logger.h
- shttps/LuaServer.cpp
- shttps/Server.cpp
- shttps/Server.h
- shttps/Shttp.cpp
- shttps/SocketControl.h
- shttps/ThreadControl.cpp
- shttps/ThreadControl.h
- src/Logger.cpp
- src/SipiCache.cpp
- src/SipiHttpServer.cpp
- src/formats/SipiIOJ2k.cpp
- src/formats/SipiIOPng.cpp
- src/formats/SipiIOTiff.cpp
- src/iiifparser/SipiSize.cpp
- src/sipi.cpp
- test/CMakeLists.txt
- test/unit/logger/CMakeLists.txt
- test/unit/logger/logger.cpp
- test/unit/logger/main.cpp
* Start using Logger.cpp in LuaServer
* add the missing log levels LuaServer used
* thereby removing remaining syslog uses
* Small test suite for Logger.cpp, fix missing quotes
* Remove log levels for now (will update, if poses problems)
* Includes some autoformatter changes
> fix: Logger.cpp in LuaServer.cpp, remove syslog, missing JSON quotes
