ext/png/CMakeLists.txt

request latest version, fixed typo in DOWNLOAD_NAME
the file name has to have an extension (bz2|tar|tgz|tar\\.gz|zip) otherwise cmake doesn't acknowledge it is a file name and still tries to parse the URL for a file name

fixing cmake typo

---

config/sipi.init-knora-test.lua

I added the same cookie handling we use for the normal configuration for the use of Sipi with Knora.

cookie handling in test preflight request

---

shttps/Server.cpp
src/SipiCache.cpp
src/formats/SipiIOJpeg.cpp

This uses `std::lock_guard` and `std::unique_lock` to lock and unlock mutexes. These objects unlock their mutexes when their destructors are called, ensuring that locks are released even if an exception is thrown. See [Difference between std::lock_guard and std::unique_lock](http://jakascorner.com/blog/2016/02/lock_guard-and-unique_lock.html) for an overview.
Closes  #91.

Use std::lock_guard and std::unique_lock

---

README.md
src/sipi.cpp

This just changes the command-line option help to suggest these
```
--config foo
-c foo
```
instead of these, which I think aren't as readable:
```
---config=foo
-cfoo
```

Show more readable command-line option syntax

---

shttps/LuaServer.cpp
shttps/LuaServer.h

If `routes` in the config file is not a Lua table, this makes Sipi say:
```
$ local/bin/sipi -c config/sipi.init-knora.lua
Sipi Version 1.0 Beta (build 2017-02-02 14:33)
Sipi Source Git-Version: 8d195e7
Error at [/Users/benjamingeer/git/Sipi/shttps/LuaServer.cpp: 2538]: Value 'routes' in config file must be a table
```
Fixes #85.

Fix crash on bad config file

---

CMakeLists.txt
include/iiifparser/SipiRotation.h
include/iiifparser/SipiSize.h
shttps/CMakeLists.txt
shttps/LuaServer.cpp
shttps/Parsing.cpp
shttps/Parsing.h
shttps/Server.cpp
src/SipiHttpServer.cpp
src/SipiImage.cpp
src/SipiLua.cpp
src/iiifparser/SipiRotation.cpp
src/iiifparser/SipiSize.cpp
src/sipi.cpp

This fixes two IIIF validation errors, so the IIIF validation tests always pass:
* Fixes #97.
* Fixes #122.
Summary of changes:
* Change the constructors of `SipiSize` and `SipiRotation` to make Sipi return a 400 Bad Request error when the IIIF size or rotation parameters are invalid.
* Collect parsing functions for integers, floats, and MIME types in `shttps::Parsing`.
* Construct a `SipiSize` on the stack instead of on the heap in `SipiLua.cpp`.
* Replace some `int` with `size_t`.
* Replace some C-style casts with `static_cast` (especially in `SipiSize.cpp`).
* Reformat some code for readability.

Improve error checking in SipiSize and SipiRotation

---

include/iiifparser/SipiRotation.h
src/iiifparser/SipiRotation.cpp

This fixes a bug in `SipiRotation` when compiled with `gcc`. I don't know why, but the `mirror` member variable wasn't always initialised to `false`, so images would be randomly mirrored. I fixed it by moving initialisation to the variable declaration.
Fixes #127.

fix (SipiRotation): Fix mirroring when Sipi is compiled with gcc

---

manual/building.rst

also changed the paragraph title as suggested by @retokromer

docs: fix build on macos, typo

---

ext/png/CMakeLists.txt

as often:
- the named version (1.6.27) of png was not available anymore (they don't keep more than the last 2 revisions)
- the generic `download latest` does not work either (file location and build script incompatibilities)
- we don't cache third party software distribution yet
so this is a temporary fix; moving to a more recent named version of libpng

moving to more recent version

---

config/sipi.fake-knora-test-config.lua
config/sipi.init-debug.lua
config/sipi.init-knora-test.lua
config/sipi.init-knora.lua
scripts/Knora_login.lua
scripts/Knora_logout.lua
scripts/get_knora_session.lua
scripts/test_knora_session_cookie.lua
shttps/LuaServer.cpp
shttps/LuaServer.h
shttps/Server.cpp
shttps/Server.h
shttps/Shttp.cpp
src/sipi.cpp
test/test_basic.py

This pull request fixes the parsing of the Knora session id from the cookie sent to Sipi on an image request (HTTP request header).
The session used to be numeric, now it isn's anymore. The regex had to be adjusted accordingly.
I have put the regex in a central place ad added a test for it.
I have also added a fix so that the script dir for Lua is addd before any Lua file is loaded.
Sipi now returns a content-type on login and logout (needed for jQuery, see <https://github.com/dhlab-basel/Knora/pull/473>).

parse Knora session id from cookie

---

src/formats/SipiIOTiff.cpp

the EXIFTAG_IMAGEUNIQUEID is a ‚\0’-terminated string and not a char-pointer with length 33 - even if it always has the length 33…
@benjamingeer Please have a look as quick as possible

Bugfix with tag EXIFTAG_IMAGEUNIQUEID

---

config/sipi.knora-docker-config.lua
config/sipi.knora-test-docker-config.lua

This should have been part of the last PR, but I forgot to update the docker configs.
- add missing exclude dirs variable to docker configuration

fix (config): add subdir exludes to docker config

---

manual/building.rst

In order to unzip Kakadu we also need unzip installed. Add `sudo apt-get install unzip` to prerequisites for Ubuntu 16.04

Add 'unzip' to Ubuntu 16.04 prerequisites

---

CMakeLists.txt
manual/building.rst
test/unit/sipiimage/CMakeLists.txt

I removed the icc header dependency for the `sipiimage` test. Since it is not needed, everything works fine.
Though in the long run, we should finde a way of allowing tests to include generated files, i.e. files which are not present when `cmake` is running.

fix (test): remove icc header dependency

---

scripts/test_functions.lua
src/SipiImage.cpp

When creating an image, we check for the consistency of the mime type indicated by the user, the original file extension and the actual mime type (determined by libmagic).
In order to check if the file extension matches a mime type, we look it up in a map whose keys are all lower-case.
This PR converts the file extension to lower-case so also upper-case extensions are found in the map.

accept upper-case file extensions for mime type check

---

ext/png/CMakeLists.txt

- Update the download URL for `libpng`
- resolves #216

fix (ext): add correct download URL

---

.travis.yml
private/.gitignore
vendor/.gitignore

Last week, I deleted the decryption key from Travis-CI after adding the new Kakadu library. Now I had to encrypt Kakadu again, so that `develop` can still work with the older version. Note to @subotic: Don't do critical stuff while ill.

build (travis): fix kakadu decoding

---

test/unit/CMakeLists.txt
test/unit/configuration/CMakeLists.txt
test/unit/configuration/configuration.cpp
test/unit/sipiimage/CMakeLists.txt
test/unit/sipiimage/sipiimage.cpp

Upstream, the path where the libraries are stored after they are built has changed.
- resolves #264

fix (test): missing libgtest

---

shttps/Server.cpp
shttps/Server.h
src/SipiHttpServer.cpp

Changed the output of info.json to use "https" for the image url if info.json is requested using https.
Its a small fix – please review ASAP

bugfix info.json: return https if SSL is used

---

src/SipiHttpServer.cpp
test/e2e/test_02_server.py

If Sipi received invalid IIIF url's with missing parts, Sipi could crash.
The bug is fixed and assorted tests for this behaviour have been added.

Bugfix: SIPI crashed for some invalid IIIF url's

---

docs/running.md

Correct link to the version 3 of the API

V2 to V3 Image API Request URI Syntax

---

docs/0-release-notes/index.md
ext/jpeg/CMakeLists.txt
ext/lcms2/CMakeLists.txt
ext/png/CMakeLists.txt

- Addition of V2 and V3 release notes
- Anti-chronological order
- Fix typos

Update release notes and reorder in an anti-chronological manner

---

Dockerfile
Makefile
test/_test_data/scripts/test_mimetype_func.lua

build: update to sipi base image with ffmpeg

---

Dockerfile
ext/zlib/CMakeLists.txt

chore(deps): add bc and imagemagick (DEV-702)

---

shttps/Server.cpp
src/SipiHttpServer.cpp

refactor(sentry): add finer grained transactions

---

CMakeLists.txt
ext/tiff/CMakeLists.txt
include/SipiImage.h
include/SipiImageError.h
src/SipiImage.cpp
src/formats/SipiIOJ2k.cpp
test/_test_data/images/unit/.gitignore
test/unit/CMakeLists.txt
test/unit/sipiimage/CMakeLists.txt
test/unit/sipiimage/sipiimage.cpp

The original TIFF has 5 components. Image was converted to JP2 but reading it back would crash as the buffer was fixed in size for 4 components and would explode ;-)
related to DEV-3229

fix: crashing on jp2 decompression

---

ext/jpeg/CMakeLists.txt

As far as I understand, the core of the issue is that the ijg library used not to correctly recognize when the 4 channel colorspace is actually YCCA, which is likely (but I can't say with 100% certainty) fixed in v9e: https://github.com/libjpeg-turbo/ijg/commit/ff9491d4e0a06542ae82367183e4548664705d80#diff-71516311e7ecc262ab53731fc7ec0ea1c6d50ff9367bdea67804f9af5c9015e5L165-R180
I discovered where the bug lies after checking that the values of a image of just cyan (100%, 0%, 0%, 0%) are 0, 255, 255, 255, so it could not have been the fault of the image profile convertor (LittleCMS, in this case. In addition, I tried setting all the parameters for LCMS manually and tested it with a byte array, which was all correct.)
Knowing the root cause, additional reports of such problems can be found, …

fix: update ijg jpeg lib to v9f, partially fixes DEV-3474

---

shttps/Connection.cpp
shttps/Connection.h
src/SipiHttpServer.cpp
test/e2e/conftest.py
test/e2e/test_02_server.py

`X-Forwarded-Proto` is now being respected in both `info.json` and `knora.json`. Repetition slightly reduced. Both are tested in `test/e2e`.
See also:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

feat: respect X-Forwarded-Proto (DEV-3499)

---

src/formats/SipiIOTiff.cpp

Since the files that are to be tested range in the multiple gigabytes (when uncompressed) and will take a lot of space and time when testing, they have not been added to the test suite. Accordingly, the fix will be tested on the dev env.
As before, when ingesting a tiled BigTiff, an error noting the incompatibility will be issued.

fix: Fix planar BigTIFF ingestion (DEV-3384)

---

src/SipiHttpServer.cpp
test/e2e/conftest.py
test/e2e/test_02_server.py

HEAD requests should return the status code without the body content. E2E Tests included.

feat: Support IIIF Image's API HEAD requests (DEV-4072)

---

src/SipiImage.cpp

Lessons learned: if a shared_ptr isn't null, that doesn't mean shared_ptr.get() isn't.

fix: Prevent exif nullptr (DEV-4521)

---

src/SipiHttpServer.cpp
test/e2e/test_02_server.py

Technically, the underlying function checks for file accessibility, but an internal server error would be inappropriate even then.

feat: return 404 for missing files (INFRA-735)

---

CMakeLists.txt
include/Logger.h
shttps/Server.cpp
shttps/Shttp.cpp
shttps/ThreadControl.cpp
src/Logger.cpp
src/SipiCache.cpp
src/SipiHttpServer.cpp
src/formats/SipiIOJ2k.cpp
src/formats/SipiIOTiff.cpp
src/sipi.cpp
test/unit/configuration/CMakeLists.txt
test/unit/sipiimage/CMakeLists.txt

Locally, sending stacktraces after segfaults (intentionally produced) won't work no matter white, despite Sentry being able to send messages. I'm willing to give this a try on the DEV environment as a last resort effort.
Replacing mostly automated with `sed -i '/);/ s:syslog(LOG_\([A-Z_]*\), *":log_\L\1(":' $(rg 'syslog\(.*LOG_' -l)`.

DEV-4658 Add symbols to Sipi stacktraces / improve logging

---

include/SipiIO.h
include/formats/SipiIOTiff.h
include/iiifparser/SipiRegion.h
src/formats/SipiIOTiff.cpp
src/handlers/iiif_handler.cpp
src/handlers/iiif_handler.hpp
src/iiifparser/SipiRegion.cpp
src/iiifparser/SipiSize.cpp
src/sipi.cpp
test/unit/handlers/iiif_handler_test.cpp
test/unit/sipiimage/sipiimage.cpp

This feature implements Pyramidal TIFF support by copying cserve's approach.
There are two main components to this feature – writing and reading TIFFs in Pyramidal TIFF format. This is enabled by `--Ctiff_pyramid=yes`.
Since SipiImage is a wrapper of a single rectangular pixel array, the reading from the pyramid selects the most appropriate resolution depending on the size reduction requested. The writing always will always write the pyramid layers, when the command line flag is enabled.
Since Pyramidal TIFF files are likely to be tile-based, tiled reading was also implemented using std::vector-based code from cserve.
A test reading and writing a Pyramidal TIFF file has also been implemented from (TiffPyramidLayers test case).
Bugs discovered while writing unit tests:
* `pct:0` as the …

feat: Pyramidal TIFF support
